POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJkYW5hMUBnbWFpbC5jb20iLCJpYXQiOjE2NDEyODY5NzB9.uhpIBYZzR5FdxOffxAWIioMbnwMsbzIhvkFYnLhHISM

{
    "author": "Dana Scully",
    "url": "dana.com",
    "title": "Autopsy records Vol 2",
    "likes": 100,
		"year": 2022
}