POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer X

{
    "author": "This author is not banned",
    "url": "witcher.com121",
    "title": "Witcher 1233",
    "likes": 3252,
		"year": 1999
}